FileSystem(Finance_Department)/Models/FileData.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FileSystem_Finance_Department_.Models
{
    public class FileData
    {
        public int FileDataId { get; set; }

        public string Date { get; set; }        
   
        public string Filename { get; set; }

        public string Filenumber { get; set; }
    
        public string Subject { get; set; }

        public string Type { get; set; }

        public string Givennumber { get; set; }

        public int Pages { get; set; }

        public string Addressee { get; set; }

        public string Sectionoforigin { get; set; }

        public string Receivedby { get; set; }

        public string Status { get; set; }

        public string Pdfdirectory { get; set; }
    }
}

FileSystem(Finance_Department)/Controllers/FileDataController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FileSystem_Finance_Department_.Models;
using System.IO;

using Rotativa;
using FileSystem_Finance_Department_.Context;

namespace FileSystem_Finance_Department_.Controllers
{
    public class FileDataController : Controller
    {
        FileSystemContext db = new FileSystemContext();


        [Authorize(Roles = "Master,Admin,User")]
        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        public ActionResult Index(string searchtxt, string fiscalmonth, string fiscalyear, string sectiontxt, string datetxt, int PageNumber = 1)
        {

            var filesview = db.FileDatas.ToList();

            if (User.IsInRole("Master") || User.IsInRole("Admin"))
            {
                filesview = db.FileDatas.ToList();
            }
            else
            {
                filesview = db.FileDatas.Where(x => x.Receivedby.Contains(User.Identity.Name)).ToList();
            }


            if (searchtxt != null && User.IsInRole("User"))
            {
                filesview = db.FileDatas.Where(x => (String.IsNullOrEmpty(searchtxt) || x.Filename.Contains(searchtxt) || x.Addressee.Contains(searchtxt) || x.Date.Contains(searchtxt) ||
                                                        x.Filename.Contains(searchtxt) || x.Filenumber.Contains(searchtxt) ||
                                                        x.Givennumber.Contains(searchtxt) || x.Sectionoforigin.Contains(searchtxt) ||
                                                        x.Subject.Contains(searchtxt) || x.Type.Contains(searchtxt)) && (x.Receivedby.Contains(User.Identity.Name))
                                                        && (String.IsNullOrEmpty(datetxt) || x.Date.Contains(datetxt))).ToList();
            }
            if (searchtxt != null && (User.IsInRole("Master") || User.IsInRole("Admin")))
            {
                filesview = db.FileDatas.Where(x => (String.IsNullOrEmpty(searchtxt) || x.Filename.Contains(searchtxt) || x.Addressee.Contains(searchtxt) || x.Date.Contains(searchtxt) ||
                                                                      x.Filename.Contains(searchtxt) || x.Filenumber.Contains(searchtxt) ||
                                                                      x.Givennumber.Contains(searchtxt) || x.Sectionoforigin.Contains(searchtxt) ||
                                                                      x.Subject.Contains(searchtxt) || x.Type.Contains(searchtxt) || x.Receivedby.Contains(searchtxt))
                                                                      && (String.IsNullOrEmpty(fiscalyear) || x.Date.Contains(fiscalyear))
                                                                      && (String.IsNullOrEmpty(fiscalmonth) || x.Date.Contains(fiscalmonth))).ToList();
            }

            return View(pagination(filesview, PageNumber));
        }

        public ActionResult PrintViewToPdf()
        {
            var report = new ActionAsPdf("Index");
            return report;
        }

        [Authorize(Roles = "Master,Admin,User")]
        public ActionResult Details(int id)
        {
            using (FileSystemContext db = new FileSystemContext())
            {
                FileData fd = db.FileDatas.FirstOrDefault(c => c.FileDataId == id);

                var report = new PartialViewAsPdf("~/Views/FileData/Details.cshtml", fd);
                return report;
            }

        }

        [Authorize(Roles = "User")]
        public ActionResult Create()
        {
            var list = new List<string>() { "Application", "DAKK", "Letter", "Minutes Of Meeting", "Summary", "Notesheet" , "Sanction Order / Release" , "Information" };
            ViewBag.list = list;
            return View();
        }

        [Authorize(Roles = "User")]
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Date,Filename,Filenumber,Subject,Type,Givennumber,Pages,Addressee,Sectionoforigin,Receivedby,Status,Pdfdirectory")] FileData fileData,FileData FD, HttpPostedFileBase file,FileDataDetail filedatadetail)
        {
           

            FD.Receivedby = User.Identity.Name.ToString();

            if (file.ContentLength > 0)
            {
                string _FileName = Path.GetFileName(file.FileName);

                string extension = Path.GetExtension(file.FileName);
                _FileName = FD.FileDataId + "-" + FD.Filename + FD.Status + extension;
                string _path = Path.Combine(Server.MapPath("~/App_Data/uploads"), _FileName);
                string uploadedfilename;
                uploadedfilename = _path;
                FD.Pdfdirectory = _FileName;

                // setting values for filedatadetails values
                filedatadetail.FileDataId = FD.FileDataId;
                filedatadetail.FilePath = _path;
                filedatadetail.Status = FD.Status;
                filedatadetail.UploadTime = DateTime.Now.ToString("MM/dd/yyyy hh:mm tt");

                file.SaveAs(uploadedfilename);
            }

            try
            {

                if (ModelState.IsValid)
                {
                    db.FileDatas.Add(FD);
                    db.FileDataDetails.Add(filedatadetail);
                    db.SaveChanges();
                    TempData["Msg"] = "Data Successfully Added";
                    return RedirectToAction("Create");
                }
            }
            catch(Exception ex)
            {
                TempData["mess"] = ex.Message;
            }

         

            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public List<FileData> pagination(List<FileData> filesview,int PageNumber)
        {
            ViewBag.TotalPages = Math.Ceiling(filesview.Count() / 4.0);
            ViewBag.PageNumber = PageNumber;

            filesview = filesview.Skip((PageNumber - 1) * 4).Take(4).ToList();

            return filesview;
        }
        public ActionResult Download(string fileName)
        {
            string path = Server.MapPath("~/App_Data/uploads");

            byte[] fileBytes = System.IO.File.ReadAllBytes(path + @"\" + fileName);

            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }
    


    }
}

FileSystem(Finance_Department)/Controllers/FileDataDetailController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FileSystem_Finance_Department_.Context;
using FileSystem_Finance_Department_.Models;
using System.IO;

namespace FileSystem_Finance_Department_.Controllers
{
    public class FileDataDetailController : Controller
    {
        private FileSystemContext db = new FileSystemContext();
       

        // GET: FileDataDetail
        public ActionResult Index(int? filedataid)
        {
            var fileid = filedataid;

                TempData["FileID"] = fileid;

                var fileDataDetails = db.FileDataDetails.Where(x => x.FileDataId == fileid).ToList();
                return View(fileDataDetails);
           
          
        }

        // GET: FileDataDetail/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FileDataDetail fileDataDetail = db.FileDataDetails.Find(id);
            if (fileDataDetail == null)
            {
                return HttpNotFound();
            }
            return View(fileDataDetail);
        }

        // GET: FileDataDetail/Create
        public ActionResult Create(int id)
        {
            return View(new FileDataDetail() {FileDataId=id });
        }

        // POST: FileDataDetail/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "FileDataDetailId,FileDataId,FilePath,Status,UploadTime")] FileDataDetail fileDataDetail, FileDataDetail fDD, HttpPostedFileBase fileupload)
        {
            if (fileupload.ContentLength > 0)
            {
                string _FileName = Path.GetFileName(fileupload.FileName);

                string extension = Path.GetExtension(fileupload.FileName);
                _FileName = fDD.FileDataId + "-" + fDD.Status + extension;
                string _path = Path.Combine(Server.MapPath("~/App_Data/uploads"), _FileName);

                fDD.FilePath = _path;

                fDD.UploadTime = DateTime.Now.ToString("MM/dd/yyyy hh:mm tt");

                fileupload.SaveAs(fDD.FilePath);
            }

            try
            {
                if (ModelState.IsValid)
                {
                    db.FileDataDetails.Add(fDD);
                    db.SaveChanges();
                    return RedirectToAction("Index", new { filedataid = fDD.FileDataId });
                }
            }
            catch(Exception ex)
            {
                TempData["Error"] = ex.Message;
            }
           
           

            return View();
        }

        // GET: FileDataDetail/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FileDataDetail fileDataDetail = db.FileDataDetails.Find(id);
            if (fileDataDetail == null)
            {
                return HttpNotFound();
            }
            ViewBag.FileDataId = new SelectList(db.FileDatas, "FileDataId", "Date", fileDataDetail.FileDataId);
            return View(fileDataDetail);
        }

        // POST: FileDataDetail/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "FileDataDetailId,FileDataId,FilePath,Status,UploadTime")] FileDataDetail fileDataDetail)
        {
            if (ModelState.IsValid)
            {
                db.Entry(fileDataDetail).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.FileDataId = new SelectList(db.FileDatas, "FileDataId", "Date", fileDataDetail.FileDataId);
            return View(fileDataDetail);
        }

        // GET: FileDataDetail/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FileDataDetail fileDataDetail = db.FileDataDetails.Find(id);
            if (fileDataDetail == null)
            {
                return HttpNotFound();
            }
            return View(fileDataDetail);
        }

        // POST: FileDataDetail/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            FileDataDetail fileDataDetail = db.FileDataDetails.Find(id);
            db.FileDataDetails.Remove(fileDataDetail);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Download(string path)
        {
            byte[] fileBytes = System.IO.File.ReadAllBytes(path);
            var  a = new FileInfo(path).Name;
            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet,a);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FileSystem(Finance_Department)/Views/FileData/Create.cshtml
@model FileSystem_Finance_Department_.Models.FileData

@{
    ViewBag.Title = "Create";
}

<h2>Add New File</h2>

@if (TempData["Msg"] != null)
{
    <h4>@TempData["Msg"].ToString()</h4>
}

@using (Html.BeginForm("Create", "FileData", FormMethod.Post, new { encType = "Multipart/Form-Data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control", placeholder = "Month/Day/Year As 01/01/2018-19" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Filename, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Filename, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Filename, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Filenumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Filenumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Filenumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Type, new SelectList(ViewBag.list), "--Select Type--", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Givennumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Givennumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Givennumber, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Pages, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pages, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pages, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Addressee, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Addressee, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Addressee, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sectionoforigin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sectionoforigin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sectionoforigin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Receivedby, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Receivedby, new { htmlAttributes = new { disabled = "disabled", @class = "form-control", @Value = User.Identity.Name.ToString() }, @readonly = "readonly" })
                @Html.ValidationMessageFor(model => model.Receivedby, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pdfdirectory, htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-md-10">
                <div>
                    <input type="file" id="file" name="file" value="BrowseFile" class="form-control" accept="application/pdf" />
                </div>
                @*@Html.TextBox("file", "", new { type = "file"})*@
                @Html.ValidationMessageFor(model => model.Pdfdirectory, "", new { @class = "text-danger" })


            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}

FileSystem(Finance_Department)/Views/FileData/Details.cshtml
@model FileSystem_Finance_Department_.Models.FileData

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>FileData</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Filename)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Filename)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Filenumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Filenumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Subject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Subject)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Givennumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Givennumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pages)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pages)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Addressee)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Addressee)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sectionoforigin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sectionoforigin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Receivedby)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Receivedby)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pdfdirectory)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pdfdirectory)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.FileDataId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

FileSystem(Finance_Department)/Views/FileData/Index.cshtml
@model IEnumerable<FileSystem_Finance_Department_.Models.FileData>

@{
    ViewBag.Title = "Index";
}


<h2>File Data View</h2>

@if (User.IsInRole("User"))
{
    @Html.ActionLink("Add New File", "Create")
}

<div class="container-fluid">

    @using (Html.BeginForm("Index", "FileData", FormMethod.Post, new { enctype = "Multipart/Form-Data" }))
    {
        <div class="form-horizontal">

            @if (User.IsInRole("Master") || User.IsInRole("Admin"))
            {
                <div class="form-group">
                    <div class="col-md-6 input-group">

                        <input type="text" name="searchtxt" class="form-control" placeholder="Enter Your Search Text Here" style="max-width:100%" />


                        <input type="text" name="fiscalmonth" class="form-control" placeholder="Enter Fiscal Month" />


                        @if (TempData["FiscalYear"] != null)
                        {
                            <input type="text" name="fiscalyear" class="form-control" value=@TempData["FiscalYear"] />
                        }
                        else
                        {
                            <input type="text" style="margin-left:9px" name="fiscalyear" class="form-control" placeholder="Enter Fiscal Year" />
                        }

                        <div>
                            <button class="btn btn-primary" type="submit">Search</button>
                        </div>

                    </div>
                </div>
            }
            else
            {
                <div class="form-group">

                    <div class="col-md-6">
                        <label id="searchlbl">Search</label>
                        <input type="text" name="searchtxt" class="form-control" placeholder="Enter Your Search Text Here" style="max-width:100%" />

                        <label id="datelbl">Date</label>
                        <input type="text" name="datetxt" class="form-control" placeholder="Enter Date Here" />
                        <div>
                            <button class="btn btn-primary" type="submit">Search</button>
                        </div>
                    </div>

                </div>
            }
        </div>
    }

    <div class="col-md-12">
        <table class="table table-bordered table-striped" style="text-align:left">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Date)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Filename)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Filenumber)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Subject)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Type)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Givennumber)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Pages)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Addressee)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Sectionoforigin)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Receivedby)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Status)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Pdfdirectory)
                </th>
                <th>

                </th>

            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Date)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Filename)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Filenumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Subject)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Type)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Givennumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Pages)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Addressee)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Sectionoforigin)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Receivedby)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Status)
                    </td>
                    <td>
                        @*@Html.DisplayFor(modelItem => item.Pdfdirectory)*@
                        @*@Html.ActionLink("Download Your File", "DownloadPDF", new { PDFFile = item.Pdfdirectory }, new { @target = "_blank" })*@
                        @Html.ActionLink("Download Your File", "Download", new { fileName = item.Pdfdirectory })
                    </td>
                    <td>
                        @Html.ActionLink("Update", "Index","FileDataDetail", new { filedataid = item.FileDataId },null) |
                        @Html.ActionLink("Print Details To PDF", "Details", new { id = item.FileDataId }) |
       
                    </td>
                </tr>
            }

        </table>

        @{
            double totalpages = ViewBag.TotalPages;

            if (totalpages > 1)
            {
                <ul class="pagination">

                    @if (ViewBag.PageNumber == 1)
                    {
                        <li>
                            @Html.ActionLink("Previous", "Index", new { PageNumber = ViewBag.PageNumber })
                        </li>
                    }
                    else
                    {
                        <li>
                            @Html.ActionLink("Previous", "Index", new { PageNumber = ViewBag.PageNumber - 1 })
                        </li>
                    }

                    @for (int i = 1; i <= totalpages; i++)
                    {

                        if (i == ViewBag.PageNumber)
                        {
                            <li class="active">
                                @Html.ActionLink(i.ToString(), "Index", new { PageNumber = i })
                            </li>
                        }
                        else
                        {
                            <li>
                                @Html.ActionLink(i.ToString(), "Index", new { PageNumber = i })
                            </li>
                        }
                    }
                    @if (ViewBag.PageNumber == totalpages)
                {
                        <li>
                            @Html.ActionLink("Next", "Index", new { PageNumber = ViewBag.PageNumber })
                        </li>
                    }
                    else
                    {
                        <li>
                            @Html.ActionLink("Next", "Index", new { PageNumber = ViewBag.PageNumber + 1 })
                        </li>
                    }


                </ul>
            }

        }
    </div>

</div>