FileSystem(Finance_Department)/Controllers/LoginController.cs
using FileSystem_Finance_Department_.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace FileSystem_Finance_Department_.Controllers
{
    public class LoginController : Controller
    {
        private FileSystemFDEntities db = new FileSystemFDEntities();
        // GET: Login
        public ActionResult Login()
        {
            return View();
        }
 
        [HttpPost]
        public ActionResult Login(Login user)
        {
            var DoesUserExist = db.Logins.Where(x => x.Username == user.Username && x.Password == user.Password).FirstOrDefault();

            if (DoesUserExist != null)
            {
                FormsAuthentication.SetAuthCookie(user.UserType, false);
                return RedirectToAction("Index", "FileData");
            }
            else
            {
                TempData["Msg"] = "Username Or Password Is Incorrect";
                return View();
            }

        }
    }
}

FileSystem(Finance_Department)/Controllers/UserDetailController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FileSystem_Finance_Department_.Context;
using FileSystem_Finance_Department_.Models;

namespace FileSystem_Finance_Department_.Controllers
{
    [Authorize(Roles ="Master")]
    public class UserDetailController : Controller
    {
        private FileSystemContext db = new FileSystemContext();

        // GET: UserDetail
        public ActionResult Index()
        {
            return View(db.Logins.ToList());
        }

        // GET: UserDetail/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Login login = db.Logins.Find(id);
            if (login == null)
            {
                return HttpNotFound();
            }
            return View(login);
        }

        // GET: UserDetail/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UserDetail/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Username,Password,UserType,CurrentSO,PreviousSO,Dateofjoining")] Login login)
        {
            if (ModelState.IsValid)
            {
                db.Logins.Add(login);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(login);
        }

        // GET: UserDetail/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Login login = db.Logins.Find(id);
            if (login == null)
            {
                return HttpNotFound();
            }
            return View(login);
        }

        // POST: UserDetail/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Username,Password,UserType,CurrentSO,PreviousSO,Dateofjoining")] Login login)
        {
            if (ModelState.IsValid)
            {
                db.Entry(login).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(login);
        }

        // GET: UserDetail/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Login login = db.Logins.Find(id);
            if (login == null)
            {
                return HttpNotFound();
            }
            return View(login);
        }

        // POST: UserDetail/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Login login = db.Logins.Find(id);
            db.Logins.Remove(login);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FileSystem(Finance_Department)/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en-us">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    <link href="~/Content/bootstrap-datetimepicker.min.css" rel="stylesheet" />
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Finance Department - File System", "Index", "FileData", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    @if (User.IsInRole("Master") || User.IsInRole("Admin") || User.IsInRole("User"))
                    {
                        <li>@Html.ActionLink("File Data", "Index", "FileData")</li>

                        if (User.IsInRole("Master"))
                        {
                            <li>@Html.ActionLink("User Detail", "Index", "UserDetail")</li>
                        }

                        <li>@Html.ActionLink("Log Out", "Logout", "Account")</li>
                        
                    }
                    else
                    {
                        <li>@Html.ActionLink("Log In", "Login", "Account")</li>
                    }

                </ul>

            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Central Record Office, Sindh</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    <script src="~/Scripts/moment.min.js"></script>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>